name: kramdown中文文档
description: kramdown的中文文档。
timezone: Asia/Shanghai
url: "https://kramdown-cn.heweather.com"
lang: zh_CN
logo: "/assets/images/brand.png"
attribution: heweather.com
github: https://github.com/heweather
icp:
  number: 京ICP备14028982号-1
  url: "http://www.beian.miit.gov.cn"
webmaster_verifications:
  google: 5mJlHKIddhky6OQT5qb7M2Uit2yzg4WGwG7JBxWQ6Cw
  bing: EDFBFE217D2B905D82BE1D5A1BC9AB28

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "html"
- scope:
    path: "_docs"
    type: "docs"
  values:
    layout: "docs-page"
    seo:
      type: "DigitalDocument"
collections:
  docs:
    permalink: "/docs/:path"
    output: true
toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6
sass:
  sass_dir: _sass
  style: compressed

exclude:
- .idea
- .git
- .gitignore
- .sass-cache
- .jekyll-cache
- README.md

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-toc
- jekyll-redirect-from
